name: CI

# 在main分支发生push事件时触发。

on:
  push:
    branches:
      - main

jobs: # 工作流
  build:
    runs-on: ubuntu-latest #运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [16.14]

    steps:
      - name: Checkout # 步骤1

        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions

      - name: Use Node.js ${{ matrix.node-version }} # 步骤2

        uses: actions/setup-node@v1 # 作用：安装nodejs

        with:
          node-version: ${{ matrix.node-version }} # 版本

      - name: Build # 安装 Node 之后就可以执行构建脚本

        run: |
          npm install pnpm -g
          pnpm i --no-frozen-lockfile
          pnpm run build

      - name: Deploy

        # 将构建产物 commit 到一个分支上，用于发布静态站点资源
        # https://github.com/peaceiris/actions-gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          # Github 会在 workflow 中自动生成 GIHUBT_TOKEN，用于认证 workflow 的运行
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 静态资源目录设置
          publish_dir: ./docs/.vuepress/dist
          # 默认发布到 gh-pages 分支上，可以指定特定的发布分支（不能选拉取代码的分支）
          publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
